# Generated by Django 3.0.7 on 2020-06-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=5)),
                ('status', models.CharField(default='inactive', max_length=254)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
